### ISSUE TITLE
license compatibility

### ISSUE THREAD

**Issue by x37v** [antoinevg/hello-daisy#1]
I'm coming here from your [board support package](https://github.com/antoinevg/daisy_bsp) (BSP)

I noticed that your `hello-daisy` example project is `MIT` licensed, but your `BSP` is `AGPL`.
I'm not sure about the differences of `GPL` vs `AGPL` but according to this [MIT FAQ](https://www.tawesoft.co.uk/kb/article/mit-license-faq) `MIT` is incompatible with `GPL` dependencies.

Considering you've authored both crates, you can probably do what you want, though I don't know if it implicitly applies a different license to your `BSP` or not..

**Comment by antoinevg** [comment]
Whoops, nice catch thank you!

`daisy_bsp` started life as an AGPL3 licensed project but I ended up splitting out all the non board-related code and forgot to change the license.

Fixed in: antoinevg/daisy_bsp@bb5302eb38f8e3953a60abf2e62ead1d118a30bf
